# Generated by Django 4.2 on 2024-02-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faceapp", "0002_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.CharField(
                choices=[
                    ("15-25", "15-25"),
                    ("26-40", "26-40"),
                    ("41-55", "41-55"),
                    ("+55", "+55"),
                ],
                default="15-25",
                max_length=5,
            ),
        ),
    ]
