# Generated by Django 4.2 on 2024-02-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faceapp", "0003_alter_user_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="predicted_face",
            field=models.CharField(default="Brad Pitt", max_length=20),
        ),
    ]
