# Generated by Django 4.2 on 2024-02-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faceapp", "0004_user_predicted_face"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
